# Generated by Django 3.1.1 on 2020-09-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes_record',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
